version: '3'

services:
  database:
    image: tullerpeton/database:${DATABASE_TAG}
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./storage/postgresql/init_api_db.sql:/docker-entrypoint-initdb.d/init_api_db.sql
    networks:
      - service-network
  service:
    depends_on:
      - database
    image: tullerpeton/service:${SERVICE_TAG}
    container_name: service
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - service-network
networks:
  service-network:
    driver: bridge