name: Build and deploy

env:
  DATABASE_TAG: v1.7
  SERVICE_TAG: v1.7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker service image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/service:${{ env.SERVICE_TAG }} --target service .
      - name: Push the service image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/service:${{ env.SERVICE_TAG }}
      - name: Build Docker database image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/database:${{ env.DATABASE_TAG }} --target database .
      - name: Push the database image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/database:${{ env.DATABASE_TAG }}
        with:
          name: Backend
          path: |
            ./docker-compose.yml
            ./storage
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dependencies
        uses: actions/download-artifact@v1
        with:
          name: Backend
      - name: Transfer dependencies to service
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "Backend"
          target: "/home/ubuntu/bot"

      - name: pull service docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/service:${{ env.API_SERVER_TAG  }}
      - name: pull database docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/database:${{ env.API_DB_TAG }}
      - name: deploy docker image
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/bot/Backend
            sudo docker-compose down
            sudo docker-compose up -d